@extends('layouts.admin')
@section('page-title','Tổng quan cửa hàng')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><p class="muted mb-0">Theo dõi hoạt động kinh doanh hôm nay.</p></div><a class="btn btn-admin" href="{{ route('admin.products.create') }}">+ Thêm sản phẩm</a></div>
@if($stats['shipping_review'] > 0)
<div class="alert alert-warning d-flex flex-wrap justify-content-between align-items-center gap-2" role="alert"><span><i class="bi bi-exclamation-triangle me-1"></i><strong>{{ $stats['shipping_review'] }} đơn GHN hoàn một phần</strong> đang chờ đối soát sản phẩm và tồn kho.</span><a class="btn btn-sm btn-warning" href="{{ route('admin.orders.index', ['shipping_review' => 1]) }}">Xử lý ngay</a></div>
@endif
<div class="row g-3 mb-4">
    <div class="col-md-6 col-xl-3"><div class="stat-card d-flex justify-content-between"><div><small class="muted">Tổng doanh thu</small><div class="stat-number">{{ number_format($stats['revenue'],0,',','.') }}đ</div><small class="text-success">Đơn đã hoàn thành</small></div><div class="stat-icon"><i class="bi bi-cash-stack"></i></div></div></div>
    <div class="col-md-6 col-xl-3"><div class="stat-card d-flex justify-content-between"><div><small class="muted">Tổng đơn hàng</small><div class="stat-number">{{ $stats['orders'] }}</div><small class="text-warning">{{ $stats['pending'] }} đơn chờ xử lý</small></div><div class="stat-icon"><i class="bi bi-receipt"></i></div></div></div>
    <div class="col-md-6 col-xl-3"><div class="stat-card d-flex justify-content-between"><div><small class="muted">Sản phẩm</small><div class="stat-number">{{ $stats['products'] }}</div><small class="muted">{{ $stats['categories'] }} danh mục</small></div><div class="stat-icon"><i class="bi bi-bag"></i></div></div></div>
    <div class="col-md-6 col-xl-3"><div class="stat-card d-flex justify-content-between"><div><small class="muted">Khách hàng</small><div class="stat-number">{{ $stats['customers'] }}</div><small class="text-success">Tài khoản khách</small></div><div class="stat-icon"><i class="bi bi-people"></i></div></div></div>
</div>
<div class="row g-4 mb-4"><div class="col-xl-8"><div class="panel p-4"><div class="d-flex justify-content-between"><div><h5 class="mb-1">Doanh thu 6 tháng gần nhất</h5><small class="muted">Chỉ tính đơn đã hoàn thành</small></div><span class="badge text-bg-light align-self-start">VNĐ</span></div><div style="height:270px"><canvas id="revenueChart"></canvas></div></div></div><div class="col-xl-4"><div class="panel p-4 h-100"><h5>Danh mục có sản phẩm</h5><p class="muted small">Số lượng sản phẩm theo danh mục</p>@forelse($categoryStats as $category)<div class="mb-3"><div class="d-flex justify-content-between small mb-1"><span>{{ $category->name }}</span><b>{{ $category->products_count }}</b></div><div class="progress" style="height:7px"><div class="progress-bar" style="width:{{ min(100,$category->products_count*20) }}%;background:#0e7490"></div></div></div>@empty<p class="muted">Chưa có dữ liệu.</p>@endforelse</div></div></div>
<div class="row g-4 mb-4"><div class="col-xl-8"><div class="panel p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Đơn hàng gần đây</h5><a href="{{ route('admin.orders.index') }}" class="small">Xem tất cả</a></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Mã đơn</th><th>Khách hàng</th><th>Tổng tiền</th><th>Trạng thái</th></tr></thead><tbody>@forelse($orders as $order)<tr><td><a href="{{ route('admin.orders.show',$order) }}" class="fw-bold text-decoration-none">{{ $order->order_code }}</a><br><small class="muted">{{ $order->created_at->format('d/m/Y') }}</small></td><td>{{ $order->customer_name }}</td><td>{{ number_format($order->total_amount,0,',','.') }}đ</td><td><span class="status status-{{ $order->status }}">{{ $order->statusLabel() }}</span></td></tr>@empty<tr><td colspan="4" class="text-center muted py-4">Chưa có đơn hàng nào.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-xl-4"><div class="panel p-4"><div class="d-flex justify-content-between"><h5>Sắp hết hàng</h5><i class="bi bi-exclamation-triangle text-warning"></i></div><p class="muted small">Theo mức cảnh báo riêng của từng biến thể.</p>@forelse($lowStock as $variant)<div class="d-flex justify-content-between align-items-center border-bottom py-2"><div><b class="small">{{ $variant->product->name }}</b><br><small class="muted">{{ $variant->color }} · {{ $variant->size }} · Ngưỡng {{ $variant->low_stock_threshold }}</small></div><span class="badge text-bg-warning">{{ $variant->stock }} còn lại</span></div>@empty<p class="text-success"><i class="bi bi-check-circle me-1"></i>Tồn kho đang ổn định.</p>@endforelse</div></div></div>
<div class="row g-4"><div class="col-xl-7"><div class="panel p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="mb-1">Sản phẩm bán chạy</h5><p class="small muted mb-0">Chỉ tính từ đơn đã hoàn thành.</p></div><i class="bi bi-graph-up-arrow text-success"></i></div>@forelse($bestSellers as $item)<div class="d-flex justify-content-between align-items-center py-2 border-bottom"><div><b>{{ $item->product_name }}</b><br><small class="muted">{{ number_format($item->units_sold) }} sản phẩm đã bán</small></div><b>{{ number_format($item->revenue,0,',','.') }}đ</b></div>@empty<p class="muted mb-0">Chưa có dữ liệu đơn hoàn thành để xếp hạng.</p>@endforelse</div></div><div class="col-xl-5"><div class="panel p-4"><h5 class="mb-2">Vận hành kho</h5><p class="muted small">Tạo phiếu nhập để tăng tồn kho có lịch sử, nhà cung cấp và giá nhập.</p><div class="d-flex gap-2"><a class="btn btn-admin btn-sm" href="{{ route('admin.purchase-receipts.create') }}">Lập phiếu nhập</a><a class="btn btn-light btn-sm" href="{{ route('admin.inventory.index') }}">Xem lịch sử</a></div></div></div></div>
@endsection
@push('scripts')
<script>window.addEventListener('DOMContentLoaded',()=>new Chart(document.getElementById('revenueChart'),{type:'line',data:{labels:@json($chartLabels),datasets:[{label:'Doanh thu',data:@json($chartData),borderColor:'#0e7490',backgroundColor:'rgba(14,116,144,.12)',fill:true,tension:.35,pointBackgroundColor:'#f97370'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{ticks:{callback:v=>new Intl.NumberFormat('vi-VN').format(v)+'đ'}}}}}));</script>
@endpush
