[program:vua-beach-queue]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/vua-beach/artisan queue:work database --sleep=2 --tries=5 --backoff=60,300,900,1800 --timeout=120 --max-time=3600
directory=/var/www/vua-beach
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=150
user=www-data
umask=027
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/vua-beach/storage/logs/queue-worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
environment=APP_ENV="production"

[program:vua-beach-scheduler]
command=/usr/bin/php /var/www/vua-beach/artisan schedule:work
directory=/var/www/vua-beach
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
umask=027
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/vua-beach/storage/logs/scheduler.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
environment=APP_ENV="production"
