@extends('layouts.admin')
@section('page-title', $coupon->exists ? 'Sửa mã ưu đãi' : 'Tạo mã ưu đãi')
@section('content')
<div class="admin-form-wrap"><form class="panel p-4 p-md-5" method="POST" action="{{ $coupon->exists ? route('admin.coupons.update', $coupon) : route('admin.coupons.store') }}">@csrf @if($coupon->exists) @method('PUT') @endif
    <div class="row g-3">
        <div class="col-md-5"><label class="form-label">Mã ưu đãi *</label><input class="form-control text-uppercase" name="code" value="{{ old('code', $coupon->code) }}" placeholder="SUMMER10" required><div class="form-text">Chỉ gồm chữ, số, dấu gạch ngang hoặc gạch dưới.</div></div>
        <div class="col-md-7"><label class="form-label">Tên chương trình *</label><input class="form-control" name="name" value="{{ old('name', $coupon->name) }}" placeholder="Giảm giá mùa hè" required></div>
        <div class="col-md-4"><label class="form-label">Loại giảm *</label><select class="form-select" name="type"><option value="percent" @selected(old('type', $coupon->type ?: 'percent') === 'percent')>Phần trăm (%)</option><option value="fixed" @selected(old('type', $coupon->type) === 'fixed')>Số tiền cố định</option></select></div>
        <div class="col-md-4"><label class="form-label">Giá trị giảm *</label><input type="number" min="1" class="form-control" name="value" value="{{ old('value', $coupon->value) }}" required></div>
        <div class="col-md-4"><label class="form-label">Giảm tối đa</label><input type="number" min="1" class="form-control" name="max_discount_amount" value="{{ old('max_discount_amount', $coupon->max_discount_amount) }}"></div>
        <div class="col-md-4"><label class="form-label">Đơn tối thiểu của phần hàng áp dụng</label><input type="number" min="0" class="form-control" name="min_order_amount" value="{{ old('min_order_amount', $coupon->min_order_amount ?? 0) }}" required></div>
        <div class="col-md-4"><label class="form-label">Tổng lượt dùng</label><input type="number" min="1" class="form-control" name="usage_limit" value="{{ old('usage_limit', $coupon->usage_limit) }}"></div>
        <div class="col-md-4"><label class="form-label">Lượt dùng/khách</label><input type="number" min="1" class="form-control" name="per_user_limit" value="{{ old('per_user_limit', $coupon->per_user_limit ?: 1) }}"><div class="form-text">Mặc định 1 lần/khách.</div></div>
        <div class="col-md-6"><label class="form-label">Bắt đầu</label><input type="datetime-local" class="form-control" name="starts_at" value="{{ old('starts_at', $coupon->starts_at?->format('Y-m-d\\TH:i')) }}"></div>
        <div class="col-md-6"><label class="form-label">Kết thúc</label><input type="datetime-local" class="form-control" name="ends_at" value="{{ old('ends_at', $coupon->ends_at?->format('Y-m-d\\TH:i')) }}"></div>
        <div class="col-12"><label class="form-label">Phạm vi áp dụng *</label><select class="form-select" name="scope" id="couponScope"><option value="all" @selected(old('scope',$coupon->scope ?: 'all') === 'all')>Toàn bộ sản phẩm trong giỏ</option><option value="products" @selected(old('scope',$coupon->scope) === 'products')>Chỉ sản phẩm được chọn</option><option value="categories" @selected(old('scope',$coupon->scope) === 'categories')>Chỉ danh mục được chọn</option></select></div>
        <div class="col-12 coupon-target" data-target="products"><label class="form-label">Sản phẩm áp dụng</label><select class="form-select" name="product_ids[]" multiple size="6">@foreach($products as $product)<option value="{{ $product->id }}" @selected(in_array($product->id, old('product_ids',$coupon->products->pluck('id')->all())))>{{ $product->name }}</option>@endforeach</select><div class="form-text">Giữ Command/Ctrl để chọn nhiều sản phẩm.</div></div>
        <div class="col-12 coupon-target" data-target="categories"><label class="form-label">Danh mục áp dụng</label><select class="form-select" name="category_ids[]" multiple size="5">@foreach($categories as $category)<option value="{{ $category->id }}" @selected(in_array($category->id, old('category_ids',$coupon->categories->pluck('id')->all())))>{{ $category->name }}</option>@endforeach</select><div class="form-text">Giảm giá chỉ tính phần tiền sản phẩm thuộc các danh mục này.</div></div>
        <div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="couponActive" @checked(old('is_active', $coupon->exists ? $coupon->is_active : true))><label class="form-check-label" for="couponActive">Kích hoạt mã ưu đãi</label></div></div>
    </div>
    <div class="admin-form-actions"><button class="btn btn-ocean">{{ $coupon->exists ? 'Lưu thay đổi' : 'Tạo mã ưu đãi' }}</button><a class="btn btn-outline-secondary" href="{{ route('admin.coupons.index') }}">Hủy</a></div>
</form></div>
@push('scripts')<script>const scope=document.querySelector('#couponScope'),targets=document.querySelectorAll('.coupon-target');const refresh=()=>targets.forEach(target=>target.hidden=target.dataset.target!==scope.value);scope.addEventListener('change',refresh);refresh();</script>@endpush
@endsection
