@extends('layouts.admin')
@section('page-title', 'Lập phiếu nhập kho')
@section('content')
<form method="POST" action="{{ route('admin.purchase-receipts.store') }}" class="panel p-4" id="receiptForm">@csrf
    <div class="row g-3 mb-4"><div class="col-md-6"><label class="form-label">Nhà cung cấp *</label><select class="form-select" name="supplier_id" required><option value="">Chọn nhà cung cấp</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(old('supplier_id') == $supplier->id)>{{ $supplier->name }}</option>@endforeach</select><small><a href="{{ route('admin.suppliers.create') }}">Thêm nhà cung cấp mới</a></small></div><div class="col-md-6"><label class="form-label">Ngày nhận hàng *</label><input class="form-control" type="datetime-local" name="received_at" required value="{{ old('received_at',now()->format('Y-m-d\\TH:i')) }}"></div><div class="col-12"><label class="form-label">Ghi chú</label><textarea class="form-control" name="note" rows="2">{{ old('note') }}</textarea></div></div>
    <div class="d-flex justify-content-between align-items-center mb-2"><h2 class="h5 mb-0">Hàng nhập</h2><button class="btn btn-sm btn-outline-primary" type="button" id="addRow"><i class="bi bi-plus-lg"></i> Thêm dòng</button></div>
    <div class="table-responsive"><table class="table align-middle" id="itemsTable"><thead><tr><th>Biến thể *</th><th width="130">Số lượng *</th><th width="190">Giá nhập/chiếc *</th><th width="180">Thành tiền</th><th width="70"></th></tr></thead><tbody></tbody><tfoot><tr><th colspan="3" class="text-end">Tổng giá nhập</th><th id="receiptTotal">0đ</th><th></th></tr></tfoot></table></div>
    <div class="mt-3 d-flex gap-2"><button class="btn btn-admin">Lưu phiếu nhập</button><a class="btn btn-light" href="{{ route('admin.purchase-receipts.index') }}">Hủy</a></div>
</form>
<template id="receiptRow"><tr><td><select class="form-select variant-select" name="items[__INDEX__][variant_id]" required><option value="">Chọn biến thể</option>@foreach($variants as $variant)<option value="{{ $variant->id }}">{{ $variant->product->name }} — {{ $variant->color }} / {{ $variant->size }} @if($variant->sku)({{ $variant->sku }})@endif · Tồn: {{ $variant->stock }}</option>@endforeach</select></td><td><input class="form-control qty-input" name="items[__INDEX__][quantity]" type="number" min="1" value="1" required></td><td><input class="form-control cost-input" name="items[__INDEX__][unit_cost]" type="number" min="0" value="0" required></td><td class="line-total">0đ</td><td><button type="button" class="btn btn-sm btn-outline-danger remove-row" aria-label="Xóa dòng"><i class="bi bi-trash"></i></button></td></tr></template>
@push('scripts')<script>
(() => { const body=document.querySelector('#itemsTable tbody'), tpl=document.querySelector('#receiptRow'), total=document.querySelector('#receiptTotal'); let index=0; const money=n=>new Intl.NumberFormat('vi-VN').format(n)+'đ'; const refresh=()=>{let sum=0; body.querySelectorAll('tr').forEach(row=>{const amount=(+row.querySelector('.qty-input').value||0)*(+row.querySelector('.cost-input').value||0);row.querySelector('.line-total').textContent=money(amount);sum+=amount});total.textContent=money(sum)}; const add=()=>{body.insertAdjacentHTML('beforeend',tpl.innerHTML.replaceAll('__INDEX__',index++));refresh()}; document.querySelector('#addRow').addEventListener('click',add); body.addEventListener('input',refresh); body.addEventListener('click',e=>{const button=e.target.closest('.remove-row');if(button){button.closest('tr').remove();refresh()}}); add(); })();
</script>@endpush
@endsection
